image: java:17-jdk
stages:
  - build
before_script:
  - export JAVA_HOME=/home/sdks/zulu-17
  - export GRADLE_USER_HOME=`pwd`/.gradle
cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
build:
  stage: build
  script:
    - ./gradlew -DpublishDocs.root=/var/www/docs/peregrine build publish publishDocs --info --no-daemon
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 days
  only:
    - master
  tags:
    - linux
