modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
logoFile = "/assets/peregrine/peregrine_logo.png"
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
authors = "${mod_authors}" #optional
description = '''${mod_description}'''
credits = """
My coffee maker for supplying the liquid patience i needed to write this library.
My keyboard and desk for withstanding my frustration when dealing with OpenGL.
"""

[[dependencies.${ mod_id }]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "embeddium"
mandatory = false
versionRange = "[0.3.30-beta.48+mc1.20.1,)"
ordering = "AFTER"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "oculus"
mandatory = false
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "CLIENT"

[features.${ mod_id }]
openGLVersion = "[4.1,)"